---
title: "Generating base maps"
author: "Shazia Ruybal-Pesántez"
date: "`r Sys.Date()`"
output: 
  html_document: 
    code_folding: hide 
    fig_width: 8
    fig_height: 6
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)

# devtools::install_github("malaria-atlas-project/malariaAtlas")

library(malariaAtlas)
library(tidyverse)
library(here)
```

Use `malariaAtlas` R package to get shape files for Admin 0 
```{r adm0 shape files}
adm0_shp_available <- malariaAtlas::listShp(admin_level = "admin0", printed = F) # 249 countries

shp_adm0 <- malariaAtlas::getShp(ISO = adm0_shp_available$iso, admin_level = "admin0")
```


Use `malariaAtlas` R package to get shape files for Admin 0 
```{r adm1 shape files}
adm1_shp_available <- malariaAtlas::listShp(admin_level = "admin1", printed = F) # 2022 adm1

shp_adm1 <- malariaAtlas::getShp(ISO = adm0_shp_available$iso, admin_level = "admin1")
```

Convert to `sf` objects
```{r}
sf_adm0 <- shp_adm0 %>% sf::st_as_sf()
sf_adm1 <- shp_adm1 %>% sf::st_as_sf()
```

Subset sSA
```{r}
africa_iso3 <- c(
  "DZA", "AGO", "BEN", "BWA", "BFA", "BDI", "CPV", "CMR", "CAF", "TCD", 
  "COM", "COD", "COG", "DJI", "EGY", "GNQ", "ERI", "SWZ", "ETH", "GAB", 
  "GMB", "GHA", "GIN", "GNB", "CIV", "KEN", "LSO", "LBR", "LBY", "MDG", 
  "MWI", "MLI", "MRT", "MUS", "MAR", "MOZ", "NAM", "NER", "NGA", "RWA", 
  "STP", "SEN", "SYC", "SLE", "SOM", "ZAF", "SSD", "SDN", "TGO", "TUN", 
  "UGA", "TZA", "ZMB", "ZWE", "ESH"
)

sf_adm0_africa <- sf_adm0 %>% filter(iso %in% africa_iso3)
sf_adm1_africa <- sf_adm1 %>% filter(iso %in% africa_iso3)
```

Save base maps
```{r}
saveRDS(sf_adm0, "data_derived/sf_admin0.rds")
saveRDS(sf_adm1, "data_derived/sf_admin1.rds")
saveRDS(sf_adm0_africa, "data_derived/sf_admin0_africa.rds")
saveRDS(sf_adm1_africa, "data_derived/sf_admin1_africa.rds")
```
